version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "AC Version"
description: "Backbone project for So Simple Grabber"
url: "http://behrooz-tahanzadeh.github.io/ssg-analyser/"
date: "July 2015"
googleAnalyticsCode: "UA-40560087-5"
